/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import quotes.quotesFile.Quotes;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
   @Test
   public void appTest(){
    Quotes quotes = new Quotes("kkkkkkk","ggggggg");

    Assertions.assertEquals("kkkkkkk",quotes.getText());
    Assertions.assertEquals("ggggggg",quotes.getAuthor());
   }


}
